Function Set-ABLObjectLocationAndMemberships {

    Write-Log -Message "Randomising ABL AD Object Location and Memberships"

    # Randomly assign each ABL object to a OU and group memberships
    $AllABLUsers = Get-ADUser -Filter { Description -eq "User generated by AutomatedBadLab" -or Description -like "Just so I dont forget my password is:*" } -Properties Description
    $AllABLGroups = Get-ADGroup -Filter { Description -eq "Group generated by AutomatedBadLab" } -Properties Description
    $AllABLOus = Get-ADOrganizationalUnit -Filter { Description -eq "OU generated by AutomatedBadLab" } -Properties Description
    $AllABLComps = Get-ADComputer -Filter { Description -eq "Computer generated by AutomatedBadLab" } -Properties Description

    foreach ($ABLUser in $AllABLUsers) {
        Move-ADObject -Identity $ABLUser -TargetPath (($AllABLOus | Get-Random).DistinguishedName)
        Add-ADGroupMember -Identity ($AllABLGroups | Get-Random) -Members $ABLUser
    }

    foreach ($ABLComp in $AllABLComps) {
        Move-ADObject -Identity $ABLComp -TargetPath (($AllABLOus | Get-Random).DistinguishedName)
        Add-ADGroupMember -Identity ($AllABLGroups | Get-Random) -Members $ABLComp
    }

    foreach ($ABLGroup in $AllABLGroups) {
        Move-ADObject -Identity $ABLGroup -TargetPath (($AllABLOus | Get-Random).DistinguishedName)
    }

    # Nest 20% of the groups
    $AllABLGroups = Get-ADGroup -Filter { Description -eq "Group generated by AutomatedBadLab" } -Properties Description

    1..[math]::Ceiling($AllABLGroups.Count * 0.2) | ForEach-Object {
        ($AllABLGroups | Get-Random) | Add-ADGroupMember -Members ($AllABLGroups | Get-Random) -ErrorAction SilentlyContinue
    }

    # Don't want any Protected Users as causes issues with exploitation
    Get-ADGroupMember -Identity 'Protected Users' | ForEach-Object { Remove-ADGroupMember -Identity 'Protected Users' -Members $_ -Confirm:$False }
}
