Function Enable-AllDCAuditingEvents {

    Write-Log -Message "Enabling all Audit Event Types"

    # Create a new GPO
    $AuditGPOName = "Domain Controllers Audit Policy"
    $GPODescription = "GPO generated by AutomatedBadLab"

    New-GPO -Name $AuditGPOName -Comment $GPODescription

    # Link the GPO to the 'Domain Controllers' OU
    $DCContainer = (Get-ADDomain).DomainControllersContainer
    New-GPLink -Name $AuditGPOName -Target $DCContainer -LinkEnabled Yes -Enforced Yes

    # Import the GPO
    $AuditGPOPath = "$PSScriptRoot\AuditSettings"
    Import-GPO -BackupGpoName $AuditGPOName -TargetName $AuditGPOName -Path $AuditGPOPath

    # Force an immediate group policy update to apply
    Invoke-GPUpdate -RandomDelayInMinutes 0 
}