# Reference - https://itm4n.github.io/printnightmare-exploitation/

Function Enable-PrintNightmare {

    Write-Host "  [+] Enabling vulnerable Point and Print Settings" -ForegroundColor Green

    # Create a new GPO
    $PrintNightmareGPOName = "Print Nightmare"
    $GPODescription = "GPO generated by AutomatedBadLab"

    New-GPO -Name $PrintNightmareGPOName -Comment $GPODescription

    # Set the required registry keys for vulnerable Point and Print settings
    $params = @{
        Name      = $PrintNightmareGPOName
        Key       = 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint'
        Type      = 'Dword'
    }

    # Set additional values under the same registry hive
    $additionalValues = @{
        'RestrictDriverInstallationToAdministrators' = 0
        'NoWarningNoElevationOnInstall' = 1
        'UpdatePromptSettings' = 2
    }

    foreach ($valueName in $additionalValues.Keys) {
        $params['ValueName'] = $valueName
        $params['Value'] = $additionalValues[$valueName]
        Set-GPRegistryValue @params
    }

    # Link the GPO to set it Domain wide
    $DomainDN = (Get-ADDomain).DistinguishedName
    New-GPLink -Name $PrintNightmareGPOName -Target $DomainDN -LinkEnabled Yes -Enforced Yes

    # Force an immediate group policy update to apply
    Invoke-GPUpdate -RandomDelayInMinutes 0 
}