Function Enable-AllKerbEncryptionTypes {

    Write-Host "  [+] Enabling all msDS-SupportedEncryptionTypes" -ForegroundColor Green

    # Create a new GPO
    $KerbEncGPOName = "KerberosEncryptionGPO"
    $GPODescription = "GPO generated by AutomatedBadLab"

    New-GPO -Name $KerbEncGPOName -Comment $GPODescription

    # Set the required registry key for the Kerberos encryption type to allow DES
    $params = @{
        Name      = $KerbEncGPOName
        Key       = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters'
        ValueName = 'SupportedEncryptionTypes'
        Type      = 'Dword'
        Value     = 30
    }

    Set-GPRegistryValue @params

    # Link the GPO to the 'Domain Controllers' OU
    $DCContainer = (Get-ADDomain).DomainControllersContainer
    New-GPLink -Name $KerbEncGPOName -Target $DCContainer -LinkEnabled Yes -Enforced Yes

    # Force an immediate group policy update to apply
    Invoke-GPUpdate -RandomDelayInMinutes 0 
}