
Function New-DCGPO {

    [CmdletBinding()]
    Param (
        [Parameter(Mandatory = $True)][string[]]$VulnUsers
    )

    Write-Host "  [+] Providing a vulnerable user rights over Domain Controllers linked GPO" -ForegroundColor Green

    # Provide a vulnerable user GPO rights
    $GPOUser = $VulnUsers | Get-Random

    # Create a new GPO
    $GPOName = "$((Get-ADDomain).NetBIOSName) Custom Domain Controllers Policy"
    $GPODescription = "GPO generated by AutomatedBadLab"

    $DCGPO = New-GPO -Name $GPOName -Comment $GPODescription

    $GPODisplayName = $DCGPO.DisplayName

    # Link the GPO to the Domain Controllers OU
    $DCContainer = (Get-ADDomain).DomainControllersContainer
    New-GPLink -Name $GPODisplayName -Target $DCContainer -Enforced Yes

    # Provide vulnerable user with full control over the GPO to abuse
    Set-GPPermissions -Name $GPODisplayName -TargetName $GPOUser -TargetType User -PermissionLevel GpoEditDeleteModifySecurity

    # Force an immediate group policy update to apply
    Invoke-GPUpdate -RandomDelayInMinutes 0 

    Write-Verbose "$GPOUser has full control over Domain Controllers GPO"

}
